spring.application.name=recommendation-service
server.port=8083

book.service.url=${BOOK_SERVICE_URL:http://localhost:8081}
reading.service.url=${READING_SERVICE_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
