name: HiBook CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  book-service:
    name: Build Book Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Book Service
        working-directory: backend/book-service
        run: ./mvnw clean package -DskipTests

  reading-service:
    name: Build Reading Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Reading Service
        working-directory: backend/reading-service
        run: ./mvnw clean package -DskipTests

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 26

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build
